### ISSUE TITLE
是否有基于 Workerman 协程 WebSocket Server 計劃 ？

### ISSUE THREAD

**Issue by liaosankai** [mix-php/mix-websocket#1]
作者你好，若为 Windows 系统用户**开发环境**兼容考虑(不依赖 wsl 情况，仍可无缝切换)，是否有计划开发基于 Workman 协程的 PHP WebSocket 服务器与客户端呢？例如 [imiphp websocket](https://github.com/imiphp/imi-project-websocket)

**Comment by onanying** [comment]
@liaosankai workerman 没有协程，而现有的 websockekt 只有 swoole 的协程版本是最友好的方式，其他多进程方式的实现是比较复杂一些，不是很友好，所以 mix 的 websocket 只支持 swoole 单进程协程版本，windows 下可以选择 wsl 开发

**Comment by liaosankai** [comment]
@onanying 这样我了解了，我会试着在 window 使用 wsl 方式来开发，感谢你的回覆 :)
